# Generated by Django 3.0.6 on 2020-06-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('content', models.TextField()),
            ],
        ),
    ]
